Python2-QAForEveryone/jenkins-testing

config/TestData.py, pages/PeoplePage.py, requirements.txt, tests/locators_dashboard_page.py, tests/locators_people_page.py, tests/test_dashboard_page.py, tests/test_people_page.py
Add test to verify title page People. [Trello](https://trello.com/c/uxSUHQKC/32-peopletitle001)
Add test to verify all elements on the page People is visible. [Trello2](https://trello.com/c/JU2jX0dy/157-peopleallelementisvisible002)
Add test to verify all elements on the page People is clickable. [Trello3](https://trello.com/c/brsSPdpX/158-peopleallelementisclickable003)
Code refactoring .
=> Add three tests PeoplePage and Refactor Mickael code

pages/BasePage.py
[Trello](https://trello.com/c/MCnuCW8s/160-add-method-getelementtext-and-dosendkeys)
I added two methods **get_element_text** and **do_send_keys** to Base Page because I think these methods will need to all.
=> Add two methods to BasePage

conftest.py
=> Conftest 1.1

conftest.py
Add time to wait for Jenkins is up
=> Conftest 1.2

pages/DashboardPage.py, tests/locators_dashboard_page.py, tests/test_dashboard_page.py
[Trello card](https://trello.com/c/byXtnzjf/162-refactoring-tests)
=> Refactoring tests

conftest.py
=> Version 1.3

tests/locators_dashboard_page.py, tests/test_dashboard_page.py
[Trello card](https://trello.com/c/X6mJY93o/139-dashboard-page-all-elements-are-visible-and-clickable-tc-023)
=> DashboardPage All_elements_are_Visible_and_Clickable

conftest.py, pages/BasePage.py, tests/locators_dashboard_page.py, tests/test_dashboard_page.py
[Trello card](https://trello.com/c/QdTtvRqS/141-dashboard-page-description-link-is-clickable-tc-025)
=> Mm Description Link: verify that it can be click and added description

conftest.py, pages/BasePage.py, tests/locators_dashboard_page.py, tests/test_dashboard_page.py
[Trello card](https://trello.com/c/CL29rUJi/26-dashboard-menu-footer-version-jenkins-is-clickable-tc-004)
=> MM Dashboard Menu: Footer - version Jenkins is Clickable TC-004

tests/locatorsDashboardLowerDropdown.py, tests/test_dashboard_lower_dropdown_page.py
added tests for click on each item in the Dashboard dropdown
https://trello.com/c/Zwv54jZ8/39-dashboard-lower-dropdown-new-view-click
https://trello.com/c/BA1xARc8/36-dashboard-lower-dropdown-manage-jenkins-click
https://trello.com/c/cUDyuTNp/33-dashboard-lower-dropdown-new-item-click
https://trello.com/c/b82JXy0S/34-dashboard-lower-dropdown-people-click
https://trello.com/c/RG9PcIzV/35-dashboard-lower-dropdown-build-history-click
https://trello.com/c/Z3uA5vPV/37-dashboard-lower-dropdown-my-views-click
https://trello.com/c/clwTDUtz/38-dashboard-lower-dropdown-lockable-resources-click
=> added tests for click on each item in the Dashboard dropdown

pages/CreateUserPage.py, pages/PeoplePage.py, tests/test_create_people_page.py
Added test_edit_user
[Trello](https://trello.com/c/5Sok0kJS/179-manage-users-tc001-verifymodifynewuser)
=> Manage Users TC_001 ->VerifyEditUser

pages/BasePage.py, pages/FolderPage.py, tests/test_folder_page.py
Added FolderPage.py, test_folder_page.py, create test_create_folder
=> JN-27 Create a Folder

pages/BasePage.py, pages/FolderPage.py, tests/test_folder_page.py
Added test_name_folder_start_special_ch (JN-47), test_name_folder_inside_special_ch(JN-52), test_name_folder_digits(JN-55),
test_name_folder_empty(JN-48), test_name_folder_start_dot(JN-53), test_name_folder_inside_dot(JN-54)
=> JN-1 Folder

pages/BasePage.py, pages/DashboardPage.py, pages/NewItemPage.py, pages/ProjectPage.py, pages/StringUtils.py, tests/test_multi_configuration_project.py
created NewItemPage, ProjectPage
StringUtils is for random string generators
4 tests added: create multi-configuration project with String, Int, String+Int, Special Symbol names
[task](https://irynab.atlassian.net/jira/software/projects/JN/boards/1?selectedIssue=JN-15)
added test for disabling the project
https://irynab.atlassian.net/jira/software/projects/JN/boards/1?selectedIssue=JN-95
added test for deleting the project
https://irynab.atlassian.net/jira/software/projects/JN/boards/1?selectedIssue=JN-97
=> JN-15 create Multi-Configuration project

.github/workflows/CI.yml, conftest.py
=> Version 2.2

pages/ManageUserPage.py, tests/test_manage_user.py
[TC-JN-41](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-41)
[TC-JN-42](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-42)
=> Manage Users > added methods Updated User and verify Login with updated user

.github/workflows/CI.yml, conftest.py
Reverts Python2-QAForEveryone/jenkins-testing#54
=> Revert "Version 2.2"

pages/ManageUserPage.py, pages/NewItemPage.py, pages/ProjectPage.py, tests/test_manage_user.py
[Jira Card](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-98)
=> Manage Users > run the build > job started

pages/BasePage.py, pages/LoginPage.py, pages/ManageUserPage.py, pages/PeoplePage.py, pages/ProjectPage.py, tests/test_manage_user.py
[Jira card](https://irynab.atlassian.net/browse/JN-106)
=> Refactoring > Manage Users > move methods to pages

conftest.py, pages/BuildHistoryPage.py, pages/ManageUserPage.py, pages/PeoplePage.py, pages/ProjectPage.py, tests/test_manage_user.py
[TC_JN_99](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-99)
[TC_JN_100](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-100)
=> Manage Users > run the build

pages/BasePage.py, pages/PeoplePage.py, pages/ProjectPage.py, tests/test_manage_user.py
[TC_JN_101](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-101)
[TC_JN_102](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-102)
=> Manage Users > run the build and review

conftest.py, pages/ProjectPage.py, tests/test_multi_configuration_project.py
added test for test_build_now
https://irynab.atlassian.net/jira/software/projects/JN/boards/1?selectedIssue=JN-114
=> JN-19 In project page user can : Run Build

pages/ProjectPage.py, tests/test_multi_configuration_project.py
added Workspace test case
https://irynab.atlassian.net/jira/software/projects/JN/boards/1?selectedIssue=JN-115
https://irynab.atlassian.net/jira/software/projects/JN/boards/1?selectedIssue=JN-20
=> JN-20 Multi-Configuration Project > user can view Workspace

pages/FolderPage.py, tests/test_folder_page.py
Added  test_create_folder_include_global_view
[Jira JN-32](https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-32)
=> Create Folder --> test_create_folder_include_global_view

pages/BuildHistoryPage.py, pages/PipelinePage.py, tests/test_pipeline.py
Added changes to the test Build now.
=> Nk pipeline

pages/ConsoleOutputPage.py, tests/test_freestyle_project.py
Test 194  "FreestyleProject> Project created: verify user can run project with "Build Now""
https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-194&text=194
Test 195  "FreestyleProject> Project created: verify user can view workspace through left sidebar
https://irynab.atlassian.net/jira/software/projects/JN/boards/1/backlog?selectedIssue=JN-195&text=195
=> Nk->Freestyle->Added test cases for 194 and 195
